version: "2"

services:
  ros-demo:
    image: ros-demo
    privileged: true
    volumes:
      # Mount the current directory do everything in /tutorial within docker
      - .:/tutorial:rw
    environment:
      - DISPLAY=1.1.1.1:0.0
    network_mode: "host"
    container_name: ros-demo
    command: "/bin/bash --init-file scripts/source-ros.sh" #source ros automatically 
